export { scanGmail, listPending, assignPedido, getDocumentEvents, exportPendingEvents, classifyAttachment, normalizePedido } from './core/ingest.js';
export { linkDocumentToPedido } from './core/link.js';
export { queryAndExportEvents } from './core/outbox.js';
export { acceptDocument, rejectDocument } from './core/acceptance.js';
export { createScan } from './core/realScan.js';
export { createAssignPedido } from './core/realAssign.js';
export type { ScanResult, ScanOptions, ScanDeps } from './core/realScan.js';
export type { AssignResult, AssignOptions, AssignDeps } from './core/realAssign.js';
export type { LinkResult } from './core/link.js';
export type { AcceptanceResult } from './core/acceptance.js';
export { exportManifest, syncManifest } from './core/syncManifest.js';
export { exportPackage } from './core/exportPackage.js';
export type { SyncManifestResult } from './core/syncManifest.js';
export type { ExportPackageResult } from './core/exportPackage.js';
export { exportReceivedDocuments, listReceivedDocuments } from './core/exportPackage.js';
export type { ExportReceivedResult, ExportReceivedOptions, ReceivedDocumentRow } from './core/exportPackage.js';
export { exportMappedDocuments, listMappedDocuments } from './core/exportPackage.js';
export type { ExportMappedResult, ExportMappedOptions, MappedDocumentRow } from './core/exportPackage.js';
